RANKED_SKINCARE_INGREDIENTS = {
    "acne": [
        "Benzoyl Peroxide",
        "Salicylic Acid",
        "Retinal",
        "Azelaic Acid",
        "Niacinamide",
        "Tea Tree Oil",
        "Zinc PCA",
        "Sulfur",
        "Betaine Salicylate",
        "Propolis",
        "Centella Asiatica",
        "Mugwort (Artemisia)",
        "Willow Bark Extract"
    ],
    "hyperpigmentation": [
        "Retinoids (Retinol, Retinal, Tretinoin)",
        "Vitamin C (Ascorbic Acid)",
        "Tranexamic Acid",
        "Niacinamide",
        "Alpha Arbutin",
        "Kojic Acid",
        "Licorice Root Extract",
        "Glutathione",
        "Arbutin",
        "Mandelic Acid",
        "Bearberry Extract",
        "Rice Extract",
        "Galactomyces Ferment Filtrate"
    ],
    "dryness": [
        "Ceramides",
        "Squalane",
        "Shea Butter",
        "Hyaluronic Acid",
        "Sodium Hyaluronate",
        "Glycerin",
        "Beta-Glucan",
        "Panthenol (Vitamin B5)",
        "Urea",
        "Royal Jelly",
        "Noni Extract",
        "Jojoba Oil",
        "Avocado Oil"
    ],
    "oily skin": [
        "Niacinamide",
        "Salicylic Acid",
        "Clay (Kaolin, Bentonite)",
        "Zinc",
        "L-Carnitine",
        "Green Tea Extract",
        "Tea Tree Oil",
        "Witch Hazel"
    ],
    "sensitivity": [
        "Centella Asiatica",
        "Panthenol",
        "Madecassoside",
        "Allantoin",
        "Colloidal Oatmeal",
        "Bisabolol",
        "Green Tea Extract",
        "Aloe Vera",
        "Mugwort (Artemisia)",
        "Heartleaf (Houttuynia Cordata)"
    ],
    "anti-aging": [
        "Retinoids (Retinol, Retinal, Bakuchiol)",
        "Peptides",
        "Vitamin C",
        "EGF (Epidermal Growth Factor)",
        "Coenzyme Q10",
        "Niacinamide",
        "Fermented Ingredients",
        "Adenosine",
        "Ginseng Extract",
        "Snail Mucin",
        "Alpha Lipoic Acid"
    ],
    "dullness": [
        "Vitamin C",
        "AHAs (Glycolic Acid, Lactic Acid)",
        "Niacinamide",
        "PHA (Gluconolactone, Lactobionic Acid)",
        "Fermented Ingredients (Galactomyces, Bifida)",
        "Licorice Root",
        "Rice Bran Extract",
        "Pearl Extract"
    ],
    "blackheads": [
        "Salicylic Acid",
        "Clay",
        "Charcoal",
        "Lactic Acid",
        "PHA (Polyhydroxy Acids)",
        "Enzymes (Papain, Bromelain)",
        "Willow Bark Extract"
    ],
    "dehydration": [
        "Hyaluronic Acid",
        "Sodium Hyaluronate",
        "Beta-Glucan",
        "Glycerin",
        "Aloe Vera",
        "Tremella Mushroom Extract",
        "Seaweed Extract",
        "Propolis",
        "Noni Extract"
    ],
    "redness/rosacea": [
        "Azelaic Acid",
        "Centella Asiatica",
        "Niacinamide",
        "Green Tea Extract",
        "Allantoin",
        "Bisabolol",
        "Heartleaf (Houttuynia Cordata)",
        "Beta-Glucan",
        "Mugwort (Artemisia)"
    ],
    "dark circles": [
        "Retinal",
        "Peptides",
        "Caffeine",
        "Niacinamide",
        "Vitamin K",
        "Ginseng Extract",
        "Snail Mucin",
        "Brightening Ferments (like Galactomyces)",
        "Licorice Root",
        "Ceramides",
        "Propolis",
        "Haloxyl"
    ],
    "uneven texture": [
        "Glycolic Acid",
        "Retinol",
        "Lactic Acid",
        "PHA (Polyhydroxy Acids)",
        "Enzymes (Papain, Bromelain)"
    ],
    "sun damage": [
        "Vitamin C",
        "Niacinamide",
        "Peptides",
        "Resveratrol",
        "Ferulic Acid",
        "Green Tea Extract",
        "Sunscreen Filters (Zinc Oxide, Titanium Dioxide)"
    ],
    "pores": [
        "Niacinamide",
        "Salicylic Acid",
        "Clay",
        "Retinal",
        "PHA",
        "Witch Hazel"
    ],
    "sun protection": [
        "Zinc Oxide",
        "Titanium Dioxide",
        "Tinosorb S (Bemotrizinol)",
        "Tinosorb M (Bisoctrizole)",
        "Mexoryl SX (Ecamsule)",
        "Mexoryl XL (Drometrizole Trisiloxane)",
        "Uvinul A Plus (Diethylamino Hydroxybenzoyl Hexyl Benzoate)",
        "Uvinul T 150 (Ethylhexyl Triazone)",
        "Avobenzone",
        "Octocrylene",
        "Homosalate",
        "Octisalate",
        "Oxybenzone",
        "Vitamin E (Tocopherol)",
        "Resveratrol",
        "Polypodium Leucotomos Extract",
        "Green Tea Extract"
    ]
}
