RANKED_SKINCARE_INGREDIENTS = {
    "acne": [
        "Benzoyl Peroxide",
        "Salicylic Acid",
        "Retinal",
        "Azelaic Acid",
        "Niacinamide",
        "Tea Tree Oil",
        "Zinc PCA",
        "Sulfur",
        "Betaine Salicylate",
        "Propolis",
        "Centella Asiatica",
        "Mugwort (Artemisia)",
        "Willow Bark Extract",
        "Bee Venom",
        "Hamamelis Virginiana (Witch Hazel)",
        "Cucumis Sativus (Cucumber) Extract"
    ],
    "hyperpigmentation": [
        "Retinoids (Retinol, Retinal, Tretinoin)",
        "Vitamin C (Ascorbic Acid)",
        "Tranexamic Acid",
        "Niacinamide",
        "Alpha Arbutin",
        "Kojic Acid",
        "Licorice Root Extract",
        "Glutathione",
        "Arbutin",
        "Mandelic Acid",
        "Bearberry Extract",
        "Rice Extract",
        "Galactomyces Ferment Filtrate",
        "Punica Granatum (Pomegranate) Extract",
        "Oryza Sativa (Rice) Bran Extract",
        "Black Rice Extract"
    ],
    "dryness": [
        "Ceramides",
        "Squalane",
        "Shea Butter",
        "Hyaluronic Acid",
        "Sodium Hyaluronate",
        "Glycerin",
        "Beta-Glucan",
        "Panthenol (Vitamin B5)",
        "Urea",
        "Royal Jelly",
        "Noni Extract",
        "Jojoba Oil",
        "Avocado Oil",
        "Honey Extract",
        "Aloe Barbadensis Leaf Water",
        "Black Rice Extract",
        "Tremella Mushroom Extract"
    ],
    "oily skin": [
        "Niacinamide",
        "Salicylic Acid",
        "Clay (Kaolin, Bentonite)",
        "Zinc",
        "L-Carnitine",
        "Green Tea Extract",
        "Tea Tree Oil",
        "Witch Hazel",
        "Lentil Seed Extract",
        "Saccharum Officinarum (Sugarcane) Extract"
    ],
    "sensitivity": [
        "Centella Asiatica",
        "Panthenol",
        "Madecassoside",
        "Allantoin",
        "Colloidal Oatmeal",
        "Bisabolol",
        "Green Tea Extract",
        "Aloe Vera",
        "Mugwort (Artemisia)",
        "Heartleaf (Houttuynia Cordata)",
        "Chamomilla Recutita (Matricaria) Flower Extract",
        "Licorice Root Extract",
        "Cucumber Extract",
        "Saponaria Officinalis Extract"
    ],
    "anti-aging": [
        "Retinoids (Retinol, Retinal, Bakuchiol)",
        "Peptides",
        "Vitamin C",
        "EGF (Epidermal Growth Factor)",
        "Coenzyme Q10",
        "Niacinamide",
        "Fermented Ingredients",
        "Adenosine",
        "Ginseng Extract",
        "Snail Mucin",
        "Alpha Lipoic Acid",
        "Copper Peptides",
        "Resveratrol",
        "Punica Granatum (Pomegranate) Extract",
        "Black Rice Extract"
    ],
    "dullness": [
        "Vitamin C",
        "AHAs (Glycolic Acid, Lactic Acid)",
        "Niacinamide",
        "PHA (Gluconolactone, Lactobionic Acid)",
        "Fermented Ingredients (Galactomyces, Bifida)",
        "Licorice Root",
        "Rice Bran Extract",
        "Pearl Extract",
        "Punica Granatum (Pomegranate) Extract",
        "Ginseng Extract",
        "Black Rice Extract"
    ],
    "blackheads": [
        "Salicylic Acid",
        "Clay",
        "Charcoal",
        "Lactic Acid",
        "PHA (Polyhydroxy Acids)",
        "Enzymes (Papain, Bromelain)",
        "Willow Bark Extract",
        "Betaine Salicylate"
    ],
    "dehydration": [
        "Hyaluronic Acid",
        "Sodium Hyaluronate",
        "Beta-Glucan",
        "Glycerin",
        "Aloe Vera",
        "Tremella Mushroom Extract",
        "Seaweed Extract",
        "Propolis",
        "Noni Extract",
        "Rice Extract",
        "Panthenol"
    ],
    "redness/rosacea": [
        "Azelaic Acid",
        "Centella Asiatica",
        "Niacinamide",
        "Green Tea Extract",
        "Allantoin",
        "Bisabolol",
        "Heartleaf (Houttuynia Cordata)",
        "Beta-Glucan",
        "Mugwort (Artemisia)",
        "Chamomile Extract"
    ],
    "dark circles": [
        "Retinal",
        "Peptides",
        "Caffeine",
        "Niacinamide",
        "Vitamin K",
        "Ginseng Extract",
        "Snail Mucin",
        "Licorice Root",
        "Ceramides",
        "Propolis",
        "Haloxyl"
    ],
    "uneven texture": [
        "Glycolic Acid",
        "Retinol",
        "Lactic Acid",
        "PHA (Polyhydroxy Acids)",
        "Enzymes (Papain, Bromelain)",
        "Salicylic Acid"
    ],
    "sun damage": [
        "Vitamin C",
        "Niacinamide",
        "Peptides",
        "Resveratrol",
        "Ferulic Acid",
        "Green Tea Extract",
        "Sunscreen Filters (Zinc Oxide, Titanium Dioxide)",
        "Tocopherol (Vitamin E)",
        "Black Rice Extract"
    ],
    "pores": [
        "Niacinamide",
        "Salicylic Acid",
        "Clay",
        "Retinal",
        "PHA",
        "Witch Hazel",
        "Tea Tree Oil"
    ],
    "sun protection": [
        "Zinc Oxide",
        "Titanium Dioxide",
        "Tinosorb S (Bemotrizinol)",
        "Tinosorb M (Bisoctrizole)",
        "Mexoryl SX (Ecamsule)",
        "Mexoryl XL (Drometrizole Trisiloxane)",
        "Uvinul A Plus (Diethylamino Hydroxybenzoyl Hexyl Benzoate)",
        "Uvinul T 150 (Ethylhexyl Triazone)",
        "Avobenzone",
        "Octocrylene",
        "Homosalate",
        "Octisalate",
        "Oxybenzone",
        "Vitamin E (Tocopherol)",
        "Resveratrol",
        "Polypodium Leucotomos Extract",
        "Green Tea Extract"
    ]
}
